USE ETRADE


SELECT *
FROM CUSTOMERS

SELECT ID, CITY
FROM CUSTOMERS

SELECT [ID], CITY
FROM CUSTOMERS

SELECT [ID], CITY, FATHERS NAME
FROM CUSTOMERS

-- YORUM SATIRI
/* YORUM SATIRI*/

--KOLON ÝSÝMLERÝ ÝKÝ KELÝMEDEN OLUÞUYORSA KÖÞELÝ PARANTEZ ÝÇÝNDE YAZILMALIDIR.
SELECT [ID], CITY, [FATHERS NAME]  
FROM CUSTOMERS

--INSERT KOMUTU ile tabloya RECORD/KAYIT eklenir ve syntaxý aþaðýdaki gibidir.

/*
INSERT INTO TABLENAME
(KOLON1, KOLON2, KOLON3,...)
VALUES
(DEGER1, DEGER2, DEGER3,...)


not: otomatik artan alan/kolon adý buraya yazýlmaz.
*/



SELECT *
FROM CUSTOMERS

-- UPDATE KOMUTU ile sütun bilgileri deðiþtirilir.KOÞUL kullanýlarak belirli deðerleri deðiþtirme þeklinde de kullanýlabilir.
-- UPDATE syntaxý aþaðýdaki gibidir.

/*
UPDATE TABLENAME
SET COLUMN1=VALUE1, COLUMN2 = VALUE2....
WHERE CONDITIONS
*/

SELECT *
FROM CUSTOMERS

UPDATE CUSTOMERS
SET NATION = 'TR'

UPDATE CUSTOMERS
SET AGE = 35

UPDATE CUSTOMERS
SET NATION = 'US', AGE = 40

SELECT DATEDIFF(YEAR, '1980-12-11', '2020-01-01')
SELECT DATEDIFF(YEAR, '1980-12-11', GETDATE())

UPDATE CUSTOMERS
SET NATION = 'US', AGE = DATEDIFF(YEAR, BIRTHDATE, GETDATE())


SELECT *
FROM CUSTOMERS


-- DELETE KOMUTU ÝLE KOÞUL BELÝRTEREK SÝLME ÝÞLEMÝ YAPILABÝLÝR.KOÞUL BELÝRTÝLMEZSE TABLONUN TAMAMI SÝLÝNÝR.
-- ANCAK ÝNDEX BÝLGÝSÝ SÝLÝNMEZ.
-- TABLOYU SÝLDÝKTEN SONRA YENÝ VERÝ EKLEDÝÐÝNÝZDE EN SON ID DEN BAÞLAYARAK YENÝ ID VERÝR.
/*
DELETE
FROM TABLENAME
WHERE CONDITIONS
*/

DELETE FROM CUSTOMERS

-- TRUNCATE KOMUTU ÝLE TABLOYU ÝNDEX DEÐERLERÝ ÝLE BÝRLÝKTE SÝLER. YENÝ KAYIT EKLEDÝÐÝNÝZDE ÝNDEX 1 DEN BAÞLAYARAK OLUÞTURULUR.
-- YANÝ TRUNCATE TABLOYU TAMAMEN BOÞALTIR. ÇOK HIZLI BÝR ÝÞLEMDÝR.
-- syntaxý aþaðýdaki gibidir.

/*
TRUNCATE TABLE TABLENAME
*/

