-- 81 ÝLÝN TOPLAM SATIÞ MÝKTARLARINI BULMAK ÝÇÝN

SELECT CITY,
MIN(TOTALPRICE) AS MINPRICE,
MAX(TOTALPRICE) AS MAXPRICE,
COUNT(FICHENO) AS ROWCOUNT_,
SUM(TOTALPRICE) AS TOTALPRICE,
AVG(TOTALPRICE) AS AVGPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE)

-- EN ÇOK SATIÞ YAPAN MAÐAZALARI GÖRMEK ÝÇÝN

SELECT CITY, SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

--EN ÇOK SATIÞ YAPAN 10 MAÐAZAYI BULMAK ÝÇÝN

SELECT TOP 10 CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

-- BÝR MAÐAZANIN GÜN BAZLI SATIÞ RAKAMLARINI GETÝRMEK ÝÇÝN

SELECT * FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
--ÖNCELÝKLE DATE SÜTUNUNDAN SADECE DATE BÝLGÝLERÝNÝ ÇEKMELÝYÝZ.
SELECT CONVERT(DATE, DATE_) AS DATE2,*
FROM SALES

-- Bu sorgu ile oluþturulan kolunu SALEs sütununa object explorer kýsmýndan ekleyelim.
--Eklediðimiz sütunu yukarýda yazdýðýmýz sorgudan da yararlanarak update edelim.

UPDATE SALES SET DATE2 = CONVERT(DATE, DATE_)

SELECT *
FROM SALES
WHERE CITY='ANKARA' AND DATE2='2019-01-01'
ORDER BY DATE_

--ÞÝMDÝ MAÐAZA BAZINDA GÜNLÜK SATIÞ RAKAMLARINI SQL ÝLE NASIL YAPACAÐIMIZI ÝNCELEYELÝM

SELECT CITY, DATE2, SUM(TOTALPRICE) AS TOTALPRI
FROM SALES
GROUP BY CITY, DATE2
ORDER BY CITY, DATE2

---BÝR GÜNÜN MAÐAZA BAZLI SATIÞLARINI GETÝRMEK ÝÇÝN

SELECT DATE2, CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
WHERE DATE2='2019-01-02'
GROUP BY DATE2, CITY
ORDER BY DATE2, CITY

SELECT DATE2, CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
WHERE DATE2='2019-01-01'
GROUP BY DATE2, CITY
ORDER BY DATE2, SUM(TOTALPRICE) DESC --EN ÇOK SATIÞ YAPANA GÖRE SIRALAMAK ÝÇÝN

-- MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETÝRMEK ÝÇÝN

--ÖNCE MONTHNAME_ ÝSÝMLÝ YENÝ BÝR SÜTUN OLUÞTURALIM
-- BUNU Object explorer dan yaptýk

-- BU yeni oluþturduðumuz kolona DATE2 sütunundan ay bilgilerini çekerek kaydedelim.

UPDATE SALES SET MONTHNAME_ ='01.OCAK' WHERE DATEPART(MONTH, DATE2)=1
UPDATE SALES SET MONTHNAME_ ='02.ÞUBAT' WHERE DATEPART(MONTH, DATE2)=2
UPDATE SALES SET MONTHNAME_ ='03.MART' WHERE DATEPART(MONTH, DATE2)=3
UPDATE SALES SET MONTHNAME_ ='04.NÝSAN' WHERE DATEPART(MONTH, DATE2)=4
UPDATE SALES SET MONTHNAME_ ='05.MAYIS' WHERE DATEPART(MONTH, DATE2)=5
UPDATE SALES SET MONTHNAME_ ='06.HAZÝRAN' WHERE DATEPART(MONTH, DATE2)=6
UPDATE SALES SET MONTHNAME_ ='07.TEMMUZ' WHERE DATEPART(MONTH, DATE2)=7
UPDATE SALES SET MONTHNAME_ ='08.AÐUSTOS' WHERE DATEPART(MONTH, DATE2)=8
UPDATE SALES SET MONTHNAME_ ='09.EYLÜL' WHERE DATEPART(MONTH, DATE2)=9
UPDATE SALES SET MONTHNAME_ ='10.EKÝM' WHERE DATEPART(MONTH, DATE2)=10
UPDATE SALES SET MONTHNAME_ ='11.KASIM' WHERE DATEPART(MONTH, DATE2)=11
UPDATE SALES SET MONTHNAME_ ='12.ARALIK' WHERE DATEPART(MONTH, DATE2)=12

SELECT * FROM SALES

SELECT MONTHNAME_, SUM(TOTALPRICE) AS TOTALPRI
FROM SALES
GROUP BY MONTHNAME_
ORDER BY MONTHNAME_

SELECT CITY, MONTHNAME_, SUM(TOTALPRICE) AS TOTALPRI
FROM SALES
GROUP BY CITY, MONTHNAME_
ORDER BY CITY, MONTHNAME_

SELECT  MONTHNAME_, CITY, SUM(TOTALPRICE) AS TOTALPRI
FROM SALES
GROUP BY MONTHNAME_, CITY
ORDER BY MONTHNAME_, CITY

--TOTALPRICE TOPLAMINA GÖRE SIRALAMAK ÝÇÝN

SELECT  MONTHNAME_, CITY, SUM(TOTALPRICE) AS TOTALPRI
FROM SALES
GROUP BY MONTHNAME_, CITY
ORDER BY MONTHNAME_, SUM(TOTALPRICE) DESC

SELECT * FROM SALES

-- KATEGORÝLERÝNE GÖRE SATIÞ MÝKTARLARINI GETÝRECEK BÝR SORGU YAZALIM

SELECT CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRI,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT
FROM SALES
GROUP BY CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4

--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRMEK ÝÇÝN

--ÖNCE ADANA ÝÇÝN OCAK AYINDA KESÝLEN FÝÞLERÝ BULALIM:
SELECT *
FROM SALES
WHERE MONTHNAME_ = '01.OCAK' AND CITY='ADANA'

SELECT FICHENO, COUNT(*)
FROM SALES
WHERE MONTHNAME_ = '01.OCAK' AND CITY='ADANA'
GROUP BY FICHENO

-- ÞÝMDÝ OCAK AYINDA TÜM ÞEHÝRLERDE KESÝLEN FÝÞ SAYILARINI BULALIM:

SELECT CITY, FICHENO, COUNT(*)  --BURADA FÝÞ SAYILARINI HER AY ÝÇÝN TEK SATIRDA GETÝRMEDÝ.
FROM SALES
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY, FICHENO
ORDER BY CITY

-- FÝÞ SAYILARINI AY BAZINDA TEK SATIRDA GÖRMEK ÝÇÝN:
SELECT CITY, COUNT(DISTINCT FICHENO), COUNT(*)  --AYNI FÝÞ NUMARASINDAN BÝRDEN FAZLA OLD. ÝÇÝN TEKRARLARI ÖNLEMEK AMACIYLA DISTINCT KULLANDIK.
FROM SALES
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY

-- BÝR MÜÞTERÝ BÝRDEN FAZLA GELÝYORSA TEKÝL MÜÞTERÝ SAYISINI BULMAK ÝÇÝN

SELECT CITY, COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS FICHECOUNT,
COUNT(*) ITEMCOUNT
FROM SALES
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY



