/* WHERE CONDITION */

SELECT *
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'

SELECT *
FROM CUSTOMERS
WHERE CITY <> 'ÝSTANBUL'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE < '19900101'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE < '19971024'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE <= '19971024'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'

SELECT *
FROM CUSTOMERS
WHERE AGE BETWEEN '22' AND '30'

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'ALÝ%'

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%ALP'

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%ALA%'

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERNAME NOT LIKE 'ALÝ%'

SELECT *
FROM CUSTOMERS
WHERE CITY IN('ÝSTANBUL','ANKARA')

SELECT *
FROM CUSTOMERS
WHERE CITY IN('ÝSTANBUL')

SELECT *
FROM CUSTOMERS
WHERE CITY IN('ÝSTANBUL','ANKARA', 'ÝZMÝR', 'BURSA')

/* WE CAN USE WHERE CONDITION WÝTH UPDATE METHOD */

UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'
UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'

/* WE CAN USE WHERE CONDITION WÝTH DELETE METHOD */

DELETE FROM CUSTOMERS WHERE ID=18

/* AND OR OPERATORS */

SELECT *
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND DISTRICT='BEYLÝKDÜZÜ'
AND DISTRICT='ESENLER' -- BURADA HATA VERÝR. ÇÜNKÜ DISTRICT HEM BEYLÝKDÜZÜ HEM ESENLER OLAMAZ.

SELECT *
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK'

SELECT *
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK' AND DISTRICT='ESENLER'

SELECT *
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'
AND GENDER='ERKEK'
AND BIRTHDATE BETWEEN '19900101' AND '20000101'

SELECT *
FROM CUSTOMERS
-- WHERE CITY='ÝSTANBUL' OR CITY='iZMÝR' OR CITY='BURSA'
WHERE CITY IN('ÝSTANBUL','ÝZMÝR','BURSA')

SELECT *
FROM CUSTOMERS
-- WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'
WHERE BIRTHDATE >= '19900101' AND BIRTHDATE <='19981231'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE <= '19900101' OR BIRTHDATE <='19981231'

SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'

SELECT *
FROM CUSTOMERS
-- WHERE NOT BIRTHDATE BETWEEN '19900101' AND '19981231'  -- BU KOMUT ALTTAKÝ ÝLE AYNI ÝÞÝ YAPIYOR
WHERE BIRTHDATE < '19900101' OR BIRTHDATE <'19981231'

/* DISTINCT METHOD

SELECT DISTINCT
COLUMN1, COLUMN2, COLUMN3,...
FROM TABLENAME
WHERE <CONDITIONS>

*/

SELECT DISTINCT CITY
FROM CUSTOMERS

SELECT CITY, DISTRICT
FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'

-- YUKARIDAKÝ SORGUDA DISTRICT SATIRINDA TEKRAR EDEN SATIRLAR DÖNMEKTEDÝR.
-- BUNU ÖNLEMEK ÝÇÝN DISTINCT METODUNU KULLANIRIZ.

SELECT DISTINCT GENDER  --SADECE ÝKÝ GENDER OLD. ÝÇÝN DISTINCT ÝLE SADECE ÝKÝ SATIR DÖNER. 
FROM CUSTOMERS

SELECT AGE
FROM CUSTOMERS

SELECT DISTINCT AGE
FROM CUSTOMERS

/* ORDER BY */

/* syntaxý aþaýðdaki gibidir.

SELECT
COLUMN1, COLUMN2, COLUMN3,...
FROM TABLENAME
WHERE <CONDITIONS>
ORDER BY COLUMN1 ASC, COLUMN2 DESC, COLUMN3 ASC...
*/

SELECT *
FROM CUSTOMERS
ORDER BY ID DESC

SELECT *
FROM CUSTOMERS
ORDER BY BIRTHDATE DESC

SELECT *
FROM CUSTOMERS
ORDER BY CITY

SELECT *
FROM CUSTOMERS
ORDER BY CITY, CUSTOMERNAME

SELECT *
FROM CUSTOMERS
ORDER BY CITY, CUSTOMERNAME DESC

SELECT *
FROM CUSTOMERS
ORDER BY CITY, DISTRICT, CUSTOMERNAME

SELECT *
FROM CUSTOMERS
WHERE GENDER = 'KADIN'
ORDER BY CITY, DISTRICT, CUSTOMERNAME

/* TOP  METODU nu sorgudan dönen kayýtlarýn bir kýsmýný görmek istediðimizde kullanýrýz*/

/* syntaxý aþaðýdaki gibidir.

SELECT TOP N
COLUMN1, COLUMN2, CLOUMN3, ...
FROM TABLENAME
WHERE <CONDITIONS>
*/

SELECT 
TOP 100 
* FROM CUSTOMERS

SELECT 
TOP 100 
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 200 
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 10 
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 50 
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 100 PERCENT
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 50 PERCENT
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 10 PERCENT
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT 
TOP 1 PERCENT
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

/* GROUP BY  METODU AGGREGATE FUNCTIONS LAR ÝLE KULLANILIR. BUNLAR:

SUM, MÝN, MAX, AVG, COUNT
*/

/* SYNTAXI AÞAÐIDAKÝ GÝBÝDÝR:

SELECT
SUM(PRICE), COUNT(ID), MIN(PRICE), MAX(PRICE),
AVG(PRICE)
FROM TABLENAME
*/

SELECT * FROM SALES

SELECT * FROM SALES ORDER BY AMOUNT

--BIR URUNDDEN EN AZ VE EN ÇOK NE KADAR SATILDIÐINI BULMAK ÝÇÝN

SELECT MIN(AMOUNT), MAX(AMOUNT), COUNT(*)  --VEYA COUNT(COLUMNNAME) ÞEKLÝNDE DE KULLANILABÝLÝR
FROM SALES

-- TOPLAM KAÇ ADET ÜRÜN SATILDIÐINI DA BULMAK ÝÇÝN

SELECT MIN(AMOUNT), MAX(AMOUNT), COUNT(FICHENO), SUM(AMOUNT)
FROM SALES

-- ORTALAMA KAÇ ADET ÜRÜN SATILDIÐINI DA BULMAK ÝÇÝN

SELECT MIN(AMOUNT), MAX(AMOUNT), COUNT(FICHENO), SUM(AMOUNT), AVG(AMOUNT)
FROM SALES

/* ÞÝMDÝ DE FÝYATLAR ÜZERÝNDEN SORGU YAPALIM */

SELECT * FROM SALES ORDER BY TOTALPRICE

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE)
FROM SALES

-- AGG FONKSÝYONLARI WHERE KOÞULU ÝLE KULLANALIM

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE)
FROM SALES
WHERE CITY ='ADANA'

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE)
FROM SALES
WHERE CITY = 'ANKARA'

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE)
FROM SALES
WHERE CITY = 'ÝSTANBUL'